# Generated by Django 4.2.28 on 2026-02-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legistar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_crawl_at', models.DateTimeField(help_text='When the last crawl completed.')),
            ],
            options={
                'verbose_name': 'Crawl metadata',
                'verbose_name_plural': 'Crawl metadata',
            },
        ),
    ]
