# Generated by Django 4.2.28 on 2026-02-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsummary",
            name="content_hash",
            field=models.CharField(db_index=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="documentsummary",
            name="model",
            field=models.CharField(default="olmo-concise", max_length=255),
        ),
        migrations.AlterField(
            model_name="documentsummary",
            name="body",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="documentsummary",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="documentsummary",
            name="headline",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="documentsummary",
            name="style",
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name="documentsummary",
            index=models.Index(
                fields=["content_hash", "style", "model"],
                name="documents_d_content_18e73f_idx",
            ),
        ),
    ]
